version: '3.1'

services:
  springboot:
    image: unitedcore/spring-boot-app
    restart: always # This will be ignored if we deploy in docker swarm
    container_name: spring-boot-app
    environment:
    - MONGO_DB_HOSTNAME=mongodb
    - MONGO_DB_USERNAME=root
    - MONGO_DB_PASSWORD=admin123
    ports:
      - 3000:8080
    networks:
      - spring-network
    working_dir: /opt/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - data:/data/db
    networks:
      - spring-network
    restart: always
volumes:
  data:
    #external: true
networks:
  spring-network:
    driver: bridge
