version: '3.1'

services:
  springboot:
    image: emortoo/springboot-app:v2
    restart: always
    container_name: springboot
    environment:
      - MONGO_DB_HOSTNAME=mongo-db
      - MONGO_DB_USERNAME=root
      - MONGO_DB_PASSWORD=admin123
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    networks:
      my_network:
        aliases:
          - springboot-app

  mongo:
    image: mongo
    container_name: springboot-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - data:/data/db
    restart: always
    networks:
      my_network:
        aliases:
          - mongo-db

volumes:
  data:

networks:
  my_network:
    driver: bridge
